# Generated by Django 5.2.4 on 2025-07-25 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('tipe', models.CharField(choices=[('admin', 'Admin'), ('staff', 'Staff')], max_length=20)),
                ('password', models.CharField(max_length=255)),
            ],
        ),
    ]
